# Generated by Django 5.0.6 on 2024-06-24 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
