# Generated by Django 5.0.6 on 2024-06-25 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0002_artwork_created_at_artwork_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="birth_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="death_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="nationality",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="artwork",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="movement",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="movement_images/"
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="artworks_images/"
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
