# Generated by Django 5.0.6 on 2024-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0003_artist_birth_year_artist_death_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="media",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="death_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
