# Generated by Django 5.0.6 on 2024-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0004_artist_media_alter_artist_birth_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="portrait",
            field=models.ImageField(
                blank=True, null=True, upload_to="artist_portraits/"
            ),
        ),
    ]
