# Generated by Django 5.0.6 on 2024-07-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0005_artist_portrait"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="sample_artwork",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sampled_artworks",
                to="artworks.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
