# Generated by Django 5.0.6 on 2024-11-03 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0006_artist_sample_artwork_alter_movement_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artworks.movement",
            ),
        ),
    ]
