# Generated by Django 5.0.6 on 2024-11-21 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0008_medium_remove_artwork_medium_artwork_medium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="medium",
        ),
        migrations.AddField(
            model_name="artwork",
            name="medium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artworks.medium",
            ),
        ),
    ]
